# Generated by Django 3.1.1 on 2020-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201001_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
