# Generated by Django 3.1.1 on 2020-10-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201018_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disc_total',
            field=models.FloatField(default=0.0),
        ),
    ]
