# Generated by Django 3.1.1 on 2020-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201006_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='user_avatar'),
        ),
    ]
