# Generated by Django 3.1.1 on 2020-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/media/user_avatar/avtar_default.jpg', null=True, upload_to='user_avatar'),
        ),
    ]
