# Generated by Django 3.1.1 on 2020-11-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
