# Generated by Django 3.1.1 on 2020-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20201116_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_category', models.CharField(max_length=50)),
                ('dish_type', models.CharField(max_length=50)),
                ('othr_details', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
