# Generated by Django 3.1.1 on 2020-12-09 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dish_sub_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
