# Generated by Django 3.1.1 on 2020-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201016_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
