# Generated by Django 3.1.1 on 2020-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_checkout_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
